# Oh My Zsh 配置
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# 中文 locale
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export LANGUAGE=zh_CN:zh

# 历史记录
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# 别名
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# 其他
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
